### ISSUE TITLE
cant install

### ISSUE THREAD

**Issue by th3impasta** [ThePlasticPotato/vs-takeoff#4]
I'm trying to install the most recent version of this mod aswell as vs2. Can someone give me some help.

**Comment by Krenity** [comment]
yea I'm struggling too, stuff is all over the place and i have no idea what to install

**Comment by Krenity** [comment]
I figured it out, you need to install these things, I recommend using a launcher like PollyMC, PrismLauncher, PollyMC (cracked minecraft) or MultiMC for better mod downloads, **TO DOWNLOAD** you need to install these mods:


Minecraft 1.18.2
```
Valkrein Skies 2 : 2.1.0-beta8
VS Takeoff : 2225bcb02b
```

This ```VS Takeoff``` version can be found in the ```Recent Versions``` at the bottom page, one you clicked on there you need to scroll down just above ```Recent Versions``` and download the bottom most ```.jar``` file, view images below for steps

![image](https://user-images.githubusercontent.com/79339771/213870972-b633dd31-6369-4b5d-9d1a-d96dd3a61f9b.png)
------------------------------
![image](https://user-images.githubusercontent.com/79339771/213870984-4f752af3-e833-4007-a770-0ba74b19f3a0.png)

**Comment by TechTastic** [comment]
Hello,

First, you are not wrong, but Takeoff has no offical releases, just on GitHub

Grab its Package as well as Valkyrien Skies 2 beta10's package to play on the latest

https://www.youtube.com/watch?v=BEocRbmM9Co

**Comment by Krenity** [comment]
> TechTastic

why is this video unlisted, it would've been so useful

**Comment by TechTastic** [comment]
> > TechTastic
> 
> why is this video unlisted, it would've been so useful

hmm, it shouldnt be, ill go poke Rango about it

**Comment by th3impasta** [comment]
i followed the steps you wrote(the video says "video unavailable") and it keeps crashing with error code 1 with no logs. Any further help?

**Comment by Krenity** [comment]
> i followed the steps you wrote(the video says "video unavailable") and it keeps crashing with error code 1 with no logs. Any further help?

If you want you can add me on discord and maybe I can help, Philip#9523

**Comment by th3impasta** [comment]
dont have discord, sorry. I managed to fix the issue slightly, because now im getting a log and its error code 2 instead.
Logs are at https://mclo.gs/M5Zl8L9

**Comment by Krenity** [comment]
> dont have discord, sorry. I managed to fix the issue slightly, because now im getting a log and its error code 2 instead.
> Logs are at https://mclo.gs/M5Zl8L9

Those logs don't look normal, it's just 25k + lines of what items are being loaded, even at the bottom, search error 2 on YouTube

**Comment by Krenity** [comment]
Try viewing the video (linked previously) in a private browser

**Comment by th3impasta** [comment]
thx i managed to watch the video with a private browser turns out i didnt install kotlin

**Comment by th3impasta** [comment]
nope now im getting this
![Screenshot 2023-01-22 073055](https://user-images.githubusercontent.com/110078150/213915910-17350fbf-19fa-459b-8bc6-5cd5df76502e.png)

**Comment by Krenity** [comment]
There you go, no problem. Also Yea, forge requires kotlin, unlike fabric where you only need takeoff and valerian skies.

**Comment by th3impasta** [comment]
here is latest.log https://pastebin.com/1gXe5eN3

**Comment by th3impasta** [comment]
heres the crash-2023-01-22_07.29.55-fml.txt file https://pastebin.com/XDtDgCES

**Comment by Krenity** [comment]
> here is latest.log https://pastebin.com/1gXe5eN3

It seems it's calling the create mod, try installing it

**Comment by th3impasta** [comment]
thx for the help, didnt know it needed create

**Comment by Krenity** [comment]
> thx for the help, didnt know it needed create

Yea I'm not sure if it's required, also I found a long that says fml core is missing mods.toml and so is javafmlanguage and a few other, I'm not sure what that means

**Comment by Krenity** [comment]
From the looks of the logs, the takeoff mod is the one that's failing to launch.
